# Generated by Django 4.2.30 on 2026-09-13 14:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=100)),
                ('stock_actual', models.IntegerField()),
                ('ventas_esperadas', models.IntegerField()),
                ('estado', models.CharField(choices=[('Optimo', 'Óptimo (Cubre mes)'), ('Alerta', 'Alerta de Quincena'), ('Critico', 'Crítico (Urgente)'), ('Invalido', 'Dato Inválido')], max_length=20)),
                ('fecha_consulta', models.DateTimeField(default=django.utils.timezone.now)),
                ('eliminado', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fecha_consulta'],
            },
        ),
    ]
